### PR TITLE
Code re-organization

### PR DESCRIPTION
**Pull request by vkuznet**
@yuyiguo , since you'll need to provide additional server/services to handle CMSSW, XrootD messages, I took an initiative to properly re-organize the codebase into proper components. I split the stompserver.go into the following files:
- main.go contains main
- fwjr.go contains code related to FWJR reports (former stompserver.go)
- utils.go file contains generic utils
- stomp.go contains code related to stomp
- config.go contains parts related to configuration
- trace.go contains code related to traces
- metrics.go contains code related to http metrics

I did NOT change the current behavior, and only split stompserver.go single file into individual files. I suggest that you learn new structure as it will allow to easily develop new components for cmssw and xrootd, please see main.go where I put comments how we can start them up. Basically we'll develop three servers, the current one (I renamed server to) fwjrServer, then the xrootdServer and cmsswServer. Each server will runs its workflow to handle individual flow of messages. All of the m can be started at once via goroutines.

### CODE REVIEW

**Comment by vkuznet** [comment]
FYI, in Go you can have single file, e.g. stompserver.go which is declared as `package main` or you can have multiple files, each has `package main` (as I proposed in this PR). In this case all individual files will be compiled as a single file and final executable will be the same.

**Comment by yuyiguo** [comment]
Hi Valentin,

What we want to do is that we can run three separated servers. In other words, each data sources has its own server. What you proposed here was one server and three gorountines run asynchronously.  I don't know enough about the gorountines to compare it with individual server.  The idea is to have less interference between different data sources.

**Comment by vkuznet** [comment]
@yuyiguo , the proposed changes has nothing to do how you'll run service. But may be you are mistaken with comments I made in a code. The changes allows to write different servers, but you can choose how to run it as you like. The solution I put in the code indeed shows how to run them as goroutines (you may think of them as different threads). If you want to run independent services, you just add a flag to the main which will start the appropriate server, e.g. instead of the following code in stompserver/main.go
```
	// start AMQ server to handle rucio tracer
        go fwjrServer()
        // when we'll develop other servers we'll call them appropriately, e.g.
        // go cmsswServer()
        // go xrootdServer()
```
you'll do something like:
```
....
        // define new flag
        var server
	flag.StringVar(&server, "sever", "", "server name to start")
....    
       if server == "fwjr" {
            fwjrServer()
       } else if server == "cmssw" {
            cmsswServer()
       } else if server == "xrootd" {
            xrootdServer()
       }
```
The changes I propose provide you ability to re-use code, structures in different servers and you'll only need to write business logic of individual servers.

**Comment by yuyiguo** [comment]
@vkuznet 

What I asked was the benefit to run gorountins instead of the separated servers since you suggested gorountins first.

**Comment by vkuznet** [comment]
The go-routine is very light thread (to fire it up there is no much resources needed like in normal languages which deal with threads). As such running single server with go-routines means that you'll manage one server but it will run 3 services (fwjr, cmssw, xrootd). If you want to run independent services you may do that too. It does not affect interaction between services (unless you write code to do that) and only affect the deployment/management process. In former case you'll have single PID to manage (even if it will run 3 services), while in latter case you'll need to manage 3 independent PIDs. But either way it does not affect performance of services.

The advantage of independent services is that you can put them in different clusters, VM, etc., and they will only run this particular services, while in single service approach it will always run 3 services (within go-routines). But the advantage of latter approach if you want some interaction between your services, e.g. send messages or calls. It all depends how you want to run them and if interaction between them will be required.

**Comment by yuyiguo** [comment]
Thanks Valentin for suggesting the code re-org.  I did it myself for me to learn Golang programing.  So I will not take this PR.

**Pull request closed without merging**
